
leagues = League.where(code: %w[mlb nfl ncaaf ncaam]).index_by(&:code)

teams_by_league = leagues.transform_values do |league|
  Team.where(league: league).index_by(&:code)
end

sources = DataSource.where(code: %w[sportsline mlb_api roto_wire]).index_by(&:code)


shared_sportsline_overrides = {
  "AAMU" => "ALAM",
  "ACU" => "ABIL",
  "AFA" => "AF",
  "AKR" => "AKRON",
  "ALBNY" => "ALBANY",
  "APP" => "APLST",
  "ARST" => "ARKST",
  "ASU" => "ARIZST",
  "AUB" => "AUBURN",
  "BALL" => "BALLST",
  "BAY" => "BAYLOR",
  "BELL" => "BELLAR",
  "BELM" => "BELMONT",
  "BGSU" => "BGREEN",
  "BRWN" => "BROWN",
  "BRY" => "BRYANT",
  "BSU" => "BOISE",
  "BUT" => "BUTLER",
  "CABP" => "CALBPTST",
  "CANI" => "CAN",
  "CARIV" => "UCRIV",
  "CASB" => "UCSB",
  "CASTN" => "CSN",
  "CASTF" => "CSFULL",
  "CCAR" => "CSTCAR",
  "CHAR" => "CHARLO",
  "CHAT" => "TNCHAT",
  "CHSO" => "CHARSO",
  "CHSU" => "CHIST",
  "CIN" => "CINCY",
  "CLEV" => "CLEVST",
  "CMU" => "CMICH",
  "COC" => "CHARLS",
  "CONN" => "UCONN",
  "COOK" => "BTHU",
  "COPP" => "COPPST",
  "COR" => "CORN",
  "CP" => "CPOLY",
  "CREIG" => "CREIGH",
  "CSU" => "COLOST",
  "CSUB" => "CSBAK",
  "DAV" => "DAVID",
  "DAY" => "DAYTON",
  "DEL" => "DE",
  "DEN" => "DENVER",
  "DET" => "DTROIT",
  "DPAUL" => "DEPAUL",
  "DREXL" => "DREXEL",
  "DRKE" => "DRAKE",
  "DSU" => "DELST",
  "EIU" => "EILL",
  "EMU" => "EMICH",
  "ETAM" => "TAMC",
  "EWU" => "EWASH",
  "FOR" => "FORD",
  "FUR" => "FURMAN",
  "FRES" => "FRESNO",
  "GASO" => "GAS",
  "GCU" => "GC",
  "GMU" => "GMASON",
  "GONZ" => "GONZAG",
  "GT" => "GATECH",
  "GTWN" => "GTOWN",
  "GW" => "GWASH",
  "HAW" => "HAWAII",
  "HC" => "HOLY",
  "HOF" => "HOFSTRA",
  "HP" => "HIGHPT",
  "IDHO" => "IDAHO",
  "INST" => "INDST",
  "ISU" => "IOWAST",
  "JAC" => "JVILLE",
  "JKST" => "JACKST",
  "JMU" => "JMAD",
  "JVST" => "JAXST",
  "KENT" => "KENTST",
  "KSU" => "KSTATE",
  "KSW" => "KENSAW",
  "KU" => "KANSAS",
  "LAM" => "LAMAR",
  "LASAL" => "LSALLE",
  "LBS" => "LNGBCH",
  "LEH" => "LEHIGH",
  "LIPS" => "LPSCMB",
  "LMC" => "LEMOYN",
  "LONG" => "LONGWD",
  "LOU" => "LVILLE",
  "LOYIL" => "LOYCHI",
  "LOYMR" => "LOYMRY",
  "LT" => "LATECH",
  "LUMD" => "LOYMD",
  "Linden" => "LINDEN",
  "M-OH" => "MIAOH",
  "MACK" => "MERMAK",
  "MARQ" => "MARQET",
  "MCNS" => "MCNSE",
  "MER" => "MERCER",
  "MHRT" => "MERCYH",
  "MIA" => "MIAMI",
  "MIZZ" => "MIZZOU",
  "MNE" => "MAINE",
  "MOKC" => "UMKC",
  "MONT" => "MNTNA",
  "MORE" => "MOREHD",
  "MORG" => "MORGAN",
  "MRST" => "MARIST",
  "MSST" => "MISSST",
  "MSU" => "MICHST",
  "MTST" => "MONST",
  "MTSTM" => "MOUNT",
  "NA" => "NAL",
  "NCCU" => "NCCEN",
  "NDSU" => "NDAKST",
  "NEAS" => "NEAST",
  "NEOM" => "NEBOM",
  "NEV" => "NEVADA",
  "NICH" => "NICHST",
  "NIU" => "NILL",
  "NJIT" => "NJTECH",
  "NKU" => "NKY",
  "NMSU" => "NMEXST",
  "NW" => "NWEST",
  "OAKD" => "OAK",
  "OKST" => "OKLAST",
  "ORE" => "OREG",
  "ORST" => "OREGST",
  "OSU" => "OHIOST",
  "PAC" => "UOP",
  "PEAY" => "AP",
  "PEPP" => "PEPPER",
  "PFW" => "IPFW",
  "PRES" => "PRESBY",
  "PRIN" => "PRINCE",
  "PRST" => "PORTST",
  "PUR" => "PURDUE",
  "QNNC" => "QUEENC",
  "QPAC" => "QUINN",
  "RADF" => "RADFRD",
  "RDER" => "RIDER",
  "RMU" => "ROB",
  "RUTG" => "RUT",
  "SAC" => "SACST",
  "SC" => "SNCLRA",
  "SCAR" => "SC",
  "SDKS" => "SDAKST",
  "SDSU" => "SDGST",
  "SELA" => "SELOU",
  "SEMO" => "SEMOST",
  "SF" => "SANFRAN",
  "SFU" => "STRFPA",
  "SH" => "SETON",
  "SHSU" => "SAMST",
  "SHU" => "SACHRT",
  "SIEN" => "SIENA",
  "SIU" => "SIL",
  "SJPA" => "STJOES",
  "SJSU" => "SJST",
  "SJU" => "STJOHN",
  "SOIN" => "SOINDI",
  "STAN" => "STNFRD",
  "STET" => "STETSON",
  "STMCA" => "MARYCA",
  "STMN" => "STTHMN",
  "STNH" => "STONH",
  "STON" => "STONYBRK",
  "STPE" => "STPETE",
  "STTL" => "SEATTLE",
  "SUU" => "SUTAH",
  "SYR" => "CUSE",
  "TAMU" => "TXAM",
  "TAR" => "TRLST",
  "TEM" => "TEMPLE",
  "TEX" => "TEXAS",
  "TLSA" => "TULSA",
  "TNTC" => "TNTECH",
  "TOL" => "TOLEDO",
  "TRGV" => "TEXPA",
  "TTU" => "TXTECH",
  "TULN" => "TULANE",
  "TXACC" => "TXAMCC",
  "TXSO" => "TEXSO",
  "TXST" => "TXSTSM",
  "UALR" => "ARKLR",
  "UCA" => "CAR",
  "UCD" => "DAVIS",
  "UCI" => "UCIRV",
  "UCSD" => "CALSD",
  "UIC" => "ILLCHI",
  "ULM" => "LAMON",
  "UMD" => "MD",
  "UMLW" => "MASLOW",
  "UNCA" => "NCASHV",
  "UNCG" => "NCGRN",
  "UNCW" => "NCWILM",
  "UNCO" => "NCOLO",
  "UND" => "NDAK",
  "UNFL" => "UNF",
  "UNH" => "NHAV",
  "UNI" => "NIOWA",
  "UNM" => "NMEX",
  "UNO" => "NORL",
  "UNT" => "NTEXAS",
  "URI" => "RI",
  "USA" => "SALA",
  "USCU" => "USCUP",
  "USF" => "SFLA",
  "USU" => "UTAHST",
  "UTM" => "TNMART",
  "UTSA" => "TXSA",
  "UVSU" => "UTVALL",
  "UWGB" => "WISGB",
  "UWM" => "MILW",
  "VALP" => "VALPO",
  "VAN" => "VANDY",
  "VRMT" => "UVM",
  "VT" => "VATECH",
  "WAG" => "WAGNER",
  "WCHST" => "WICHST",
  "WCU" => "WCAR",
  "WEB" => "WBRST",
  "WEBB" => "GWEBB",
  "WEGA" => "WESTGA",
  "WINT" => "WINTHR",
  "WIS" => "WISC",
  "WIU" => "WIL",
  "WKU" => "WKY",
  "WMRY" => "WMMARY",
  "WMU" => "WMICH",
  "WOF" => "WOFF",
  "WRIG" => "WRIGHT",
  "WSU" => "WASHST",
  "XAV" => "XAVIER"
}


overrides_by_league_and_source = {
  "mlb" => {
    "sportsline" => {
      "KCR" => "KC",
      "SDP" => "SD",
      "SFG" => "SF",
      "TBR" => "TB",
      "WSN" => "WAS"
    },
    "mlb_api" => {
      "ARI" => "AZ",
      "CHW" => "CWS",
      "KCR" => "KC",
      "SDP" => "SD",
      "SFG" => "SF",
      "TBR" => "TB",
      "WSN" => "WSH"
    },
    "roto_wire" => {
      "CHW" => "CWS",
      "KCR" => "KC",
      "SDP" => "SD",
      "SFG" => "SF",
      "TBR" => "TB",
      "WSN" => "WSH"
    }
    # fan_graphs has no overrides — all team codes match
  },
  "nfl" => {
    "sportsline" => {
      "GNB" => "GB",
      "JAX" => "JAC",
      "KAN" => "KC",
      "NOR" => "NO",
      "NWE" => "NE",
      "SFO" => "SF",
      "TAM" => "TB",
    }
  },
  "ncaaf" => {
    "sportsline" => shared_sportsline_overrides
  },
  "ncaam" => {
    "sportsline" => shared_sportsline_overrides
  }

}

# Step 4: Seed team identifiers
overrides_by_league_and_source.each do |league_code, source_overrides|
  league = leagues.fetch(league_code)
  teams  = teams_by_league.fetch(league_code)

  source_overrides.each do |source_code, team_overrides|
    source = sources.fetch(source_code)

    teams.each do |internal_code, team|
      external_code = team_overrides[internal_code] || internal_code

      TeamIdentifier.find_or_create_by!(
        team: team,
        league: league,
        data_source: source,
        external_code: external_code,
        active: true
      )
    end
  end
end