mlb = League.find_by!(code: 'mlb')
nfl = League.find_by!(code: 'nfl')
ncaaf = League.find_by!(code: 'ncaaf')
ncaam = League.find_by!(code: 'ncaam')

mlb_teams = [
  { code: 'ATH', location_name: '',  nickname: 'Athletics' },
  { code: 'ARI', location_name: 'Arizona', nickname: 'Diamondbacks' },
  { code: 'ATL', location_name: 'Atlanta', nickname: 'Braves' },
  { code: 'BAL', location_name: 'Baltimore', nickname: 'Orioles' },
  { code: 'BOS', location_name: 'Boston', nickname: 'Red Sox' },
  { code: 'CHC', location_name: 'Chicago', nickname: 'Cubs' },
  { code: 'CHW', location_name: 'Chicago', nickname: 'White Sox' },
  { code: 'CIN', location_name: 'Cincinnati', nickname: 'Reds' },
  { code: 'CLE', location_name: 'Cleveland', nickname: 'Guardians' },
  { code: 'COL', location_name: 'Colorado', nickname: 'Rockies' },
  { code: 'DET', location_name: 'Detroit', nickname: 'Tigers' },
  { code: 'HOU', location_name: 'Houston', nickname: 'Astros' },
  { code: 'KCR', location_name: 'Kansas City', nickname: 'Royals' },
  { code: 'LAA', location_name: 'Los Angeles', nickname: 'Angels' },
  { code: 'LAD', location_name: 'Los Angeles', nickname: 'Dodgers' },
  { code: 'MIA', location_name: 'Miami', nickname: 'Marlins' },
  { code: 'MIL', location_name: 'Milwaukee', nickname: 'Brewers' },
  { code: 'MIN', location_name: 'Minnesota', nickname: 'Twins' },
  { code: 'NYM', location_name: 'New York', nickname: 'Mets' },
  { code: 'NYY', location_name: 'New York', nickname: 'Yankees' },
  { code: 'PHI', location_name: 'Philadelphia', nickname: 'Phillies' },
  { code: 'PIT', location_name: 'Pittsburgh', nickname: 'Pirates' },
  { code: 'SEA', location_name: 'Seattle', nickname: 'Mariners' },
  { code: 'SDP', location_name: 'San Diego', nickname: 'Padres' },
  { code: 'SFG', location_name: 'San Francisco', nickname: 'Giants' },
  { code: 'STL', location_name: 'Saint Louis', nickname: 'Cardinals' },
  { code: 'TBR', location_name: 'Tampa Bay', nickname: 'Rays' },
  { code: 'TEX', location_name: 'Texas', nickname: 'Rangers' },
  { code: 'TOR', location_name: 'Toronto', nickname: 'Blue Jays' },
  { code: 'WSN', location_name: 'Washington', nickname: 'Nationals' }
]

mlb_teams.each do |attrs|
  team = Team.find_or_create_by!(code: attrs[:code]) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
  
  # Associate team with MLB league
  team.leagues << mlb unless team.leagues.include?(mlb)
end

nfl_teams = [
  { code: 'ARI', location_name: 'Arizona',  nickname: 'Cardinals' },
  { code: 'ATL', location_name: 'Atlanta',  nickname: 'Falcons' },
  { code: 'BAL', location_name: 'Baltimore',  nickname: 'Ravens' },
  { code: 'BUF', location_name: 'Buffalo',  nickname: 'Bills' },
  { code: 'CAR', location_name: 'Carolina',  nickname: 'Panthers' },
  { code: 'CHI', location_name: 'Chicago',  nickname: 'Bears' },
  { code: 'CIN', location_name: 'Cincinnati',  nickname: 'Bengals' },
  { code: 'CLE', location_name: 'Cleveland',  nickname: 'Browns' },
  { code: 'DAL', location_name: 'Dallas',  nickname: 'Cowboys' },
  { code: 'DEN', location_name: 'Denver',  nickname: 'Broncos' },
  { code: 'DET', location_name: 'Detroit',  nickname: 'Lions' },
  { code: 'GNB', location_name: 'Green Bay',  nickname: 'Packers' },
  { code: 'HOU', location_name: 'Houston',  nickname: 'Texans' },
  { code: 'IND', location_name: 'Indianapolis',  nickname: 'Colts' },
  { code: 'JAX', location_name: 'Jacksonville',  nickname: 'Jaguars' },
  { code: 'KAN', location_name: 'Kansas City',  nickname: 'Chiefs' },
  { code: 'LAC', location_name: 'Los Angeles',  nickname: 'Chargers' },
  { code: 'LAR', location_name: 'Los Angeles',  nickname: 'Rams' },
  { code: 'LVR', location_name: 'Las Vegas',  nickname: 'Raiders' },
  { code: 'MIA', location_name: 'Miami',  nickname: 'Dolphins' },
  { code: 'MIN', location_name: 'Minnesota',  nickname: 'Vikings' },
  { code: 'NOR', location_name: 'New Orleans',  nickname: 'Saints' },
  { code: 'NWE', location_name: 'New England',  nickname: 'Patriots' },
  { code: 'NYG', location_name: 'New York',  nickname: 'Giants' },
  { code: 'NYJ', location_name: 'New York',  nickname: 'Jets' },
  { code: 'PHI', location_name: 'Philadelphia',  nickname: 'Eagles' },
  { code: 'PIT', location_name: 'Pittsburgh',  nickname: 'Steelers' },
  { code: 'SEA', location_name: 'Seattle',  nickname: 'Seahawks' },
  { code: 'SFO', location_name: 'San Francisco',  nickname: '49ers' },
  { code: 'TAM', location_name: 'Tampa Bay',  nickname: 'Buccaneers' },
  { code: 'TEN', location_name: 'Tennessee',  nickname: 'Titans' },
  { code: 'WAS', location_name: 'Washington',  nickname: 'Commanders' }
]

nfl_teams.each do |attrs|
  team = Team.find_or_create_by!(code: attrs[:code]) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
  
  team.leagues << nfl unless team.leagues.include?(nfl)
end

ncaa_teams = [
  { code: 'AAMU', location_name: 'Alabama A&M', nickname: 'Bulldogs' },
  { code: 'ACU', location_name: 'Abilene Christian', nickname: 'Wildcats' },
  { code: 'AFA', location_name: 'Air Force', nickname: 'Falcons' },
  { code: 'AKR', location_name: 'Akron', nickname: 'Zips' },
  { code: 'ALBNY', location_name: 'Albany', nickname: 'Great Danes' },
  { code: 'ALCN', location_name: 'Alcorn St.', nickname: 'Braves' },
  { code: 'ALST', location_name: 'Alabama St.', nickname: 'Hornets' },
  { code: 'AMER', location_name: 'American', nickname: 'Eagles' },
  { code: 'APP', location_name: 'App St.', nickname: 'Mountaineers' },
  { code: 'ARIZ', location_name: 'Arizona', nickname: 'Wildcats' },
  { code: 'ARK', location_name: 'Arkansas', nickname: 'Razorbacks' },
  { code: 'ARMY', location_name: 'Army', nickname: 'Black Knights' },
  { code: 'ARPB', location_name: 'Arkansas-Pine Bluff', nickname: 'Golden Lions' },
  { code: 'ARST', location_name: 'Arkansas St.', nickname: 'Red Wolves' },
  { code: 'ASU', location_name: 'Arizona St.', nickname: 'Sun Devils' },
  { code: 'AUB', location_name: 'Auburn', nickname: 'Tigers' },
  { code: 'BALL', location_name: 'Ball St.', nickname: 'Cardinals' },
  { code: 'BAMA', location_name: 'Alabama', nickname: 'Crimson Tide' },
  { code: 'BAY', location_name: 'Baylor', nickname: 'Bears' },
  { code: 'BC', location_name: 'Boston College', nickname: 'Eagles' },
  { code: 'BELL', location_name: 'Bellarmine', nickname: 'Knights' },
  { code: 'BELM', location_name: 'Belmont', nickname: 'Bruins' },
  { code: 'BGSU', location_name: 'Bowling Green', nickname: 'Falcons' },
  { code: 'BING', location_name: 'Binghamton', nickname: 'Bearcats' },
  { code: 'BRAD', location_name: 'Bradley', nickname: 'Braves' },
  { code: 'BRWN', location_name: 'Brown', nickname: 'Bears' },
  { code: 'BRY', location_name: 'Bryant', nickname: 'Bulldogs' },
  { code: 'BRYST', location_name: 'Bryant & Stratton', nickname: 'Bobcats' },
  { code: 'BSU', location_name: 'Boise St.', nickname: 'Broncos' },
  { code: 'BUCK', location_name: 'Bucknell', nickname: 'Bison' },
  { code: 'BUFF', location_name: 'Buffalo', nickname: 'Bulls' },
  { code: 'BU', location_name: 'Boston University', nickname: 'Terriers' },
  { code: 'BUT', location_name: 'Butler', nickname: 'Bulldogs' },
  { code: 'BYU', location_name: 'Brigham Young', nickname: 'Cougars' },
  { code: 'CABP', location_name: 'California Baptist', nickname: 'Lancers' },
  { code: 'CAL', location_name: 'California', nickname: 'Bears' },
  { code: 'CAMP', location_name: 'Campbell', nickname: 'Fighting Camels' },
  { code: 'CANI', location_name: 'Canisius', nickname: 'Golden Griffins' },
  { code: 'CARIV', location_name: 'UC Riverside', nickname: 'Highlanders' },
  { code: 'CASB', location_name: 'UC Santa Barbara', nickname: 'Gauchos' },
  { code: 'CASTN', location_name: 'Cal State Northridge', nickname: 'Matadors' },
  { code: 'CASTF', location_name: 'Cal State Fullerton', nickname: 'Titans' },
  { code: 'CCAR', location_name: 'Coastal Carolina', nickname: 'Chanticleers' },
  { code: 'CCTST', location_name: 'Central Connecticut', nickname: 'Blue Devils' },
  { code: 'CHAR', location_name: 'Charlotte', nickname: '49ers' },
  { code: 'CHAT', location_name: 'Chattanooga', nickname: 'Mocs' },
  { code: 'CHSO', location_name: 'Charleston Southern', nickname: 'Buccaneers' },
  { code: 'CHSU', location_name: 'Chicago St.', nickname: 'Cougars' },
  { code: 'CIN', location_name: 'Cincinnati', nickname: 'Bearcats' },
  { code: 'CIT', location_name: 'The Citadel', nickname: 'Bulldogs' },
  { code: 'CLEM', location_name: 'Clemson', nickname: 'Tigers' },
  { code: 'CLEV', location_name: 'Cleveland St.', nickname: 'Vikings' },
  { code: 'CLMB', location_name: 'Columbia', nickname: 'Lions' },
  { code: 'CMU', location_name: 'Central Michigan', nickname: 'Chippewas' },
  { code: 'COC', location_name: 'Charleston', nickname: 'Cougars' },
  { code: 'COLO', location_name: 'Colorado', nickname: 'Buffaloes' },
  { code: 'COLG', location_name: 'Colgate', nickname: 'Raiders' },
  { code: 'CONN', location_name: 'Connecticut', nickname: 'Huskies' },
  { code: 'COOK', location_name: 'Bethune-Cookman', nickname: 'Wildcats' },
  { code: 'COPP', location_name: 'Coppin St.', nickname: 'Eagles' },
  { code: 'COR', location_name: 'Cornell', nickname: 'Big Red' },
  { code: 'CP', location_name: 'Cal Poly', nickname: 'Mustangs' },
  { code: 'CREIG', location_name: 'Creighton', nickname: 'Bluejays' },
  { code: 'CSU', location_name: 'Colorado St.', nickname: 'Rams' },
  { code: 'CSUB', location_name: 'Cal St. Bakersfield', nickname: 'Roadrunners' },
  { code: 'DART', location_name: 'Dartmouth', nickname: 'Big Green' },
  { code: 'DAV', location_name: 'Davidson', nickname: 'Wildcats' },
  { code: 'DAY', location_name: 'Dayton', nickname: 'Flyers' },
  { code: 'DEL', location_name: 'Delaware', nickname: 'Blue Hens' },
  { code: 'DEN', location_name: 'Denver', nickname: 'Pioneers' },
  { code: 'DET', location_name: 'Detroit Mercy', nickname: 'Titans' },
  { code: 'DPAUL', location_name: 'DePaul', nickname: 'Blue Demons' },
  { code: 'DREXL', location_name: 'Drexel', nickname: 'Dragons' },
  { code: 'DRKE', location_name: 'Drake', nickname: 'Bulldogs' },
  { code: 'DSU', location_name: 'Delaware St.', nickname: 'Hornets' },
  { code: 'DUKE', location_name: 'Duke', nickname: 'Blue Devils' },
  { code: 'DUQ', location_name: 'Duquesne', nickname: 'Dukes' },
  { code: 'ECU', location_name: 'East Carolina', nickname: 'Pirates' },
  { code: 'EIU', location_name: 'Eastern Illinois', nickname: 'Panthers' },
  { code: 'EKY', location_name: 'Eastern Kentucky', nickname: 'Colonels' },
  { code: 'ELON', location_name: 'Elon', nickname: 'Phoenix' },
  { code: 'EMU', location_name: 'Eastern Michigan', nickname: 'Eagles' },
  { code: 'ETAM', location_name: 'East Texas A&M', nickname: 'Lions' },
  { code: 'ETNST', location_name: 'East Tennessee St.', nickname: 'Buccaneers' },
  { code: 'EVAN', location_name: 'Evansville', nickname: 'Purple Aces' },
  { code: 'EWU', location_name: 'Eastern Washington', nickname: 'Eagles' },
  { code: 'FAIR', location_name: 'Fairfield', nickname: 'Stags' },
  { code: 'FAMU', location_name: 'Florida A&M', nickname: 'Rattlers' },
  { code: 'FAU', location_name: 'Florida Atlantic', nickname: 'Owls' },
  { code: 'FDU', location_name: 'Fairleigh Dickinson', nickname: 'Knights' },
  { code: 'FGCU', location_name: 'Florida Gulf Coast', nickname: 'Eagles' },
  { code: 'FIU', location_name: 'Florida International', nickname: 'Panthers' },
  { code: 'FLA', location_name: 'Florida', nickname: 'Gators' },
  { code: 'FOR', location_name: 'Fordham', nickname: 'Rams' },
  { code: 'FRES', location_name: 'Fresno St.', nickname: 'Bulldogs' },
  { code: 'FSU', location_name: 'Florida St.', nickname: 'Seminoles' },
  { code: 'FUR', location_name: 'Furman', nickname: 'Paladins' },
  { code: 'GASO', location_name: 'Georgia Southern', nickname: 'Eagles' },
  { code: 'GAST', location_name: 'Georgia St.', nickname: 'Panthers' },
  { code: 'GCU', location_name: 'Grand Canyon', nickname: 'Antelopes' },
  { code: 'GMU', location_name: 'George Mason', nickname: 'Patriots' },
  { code: 'GONZ', location_name: 'Gonzaga', nickname: 'Bulldogs' },
  { code: 'GRAM', location_name: 'Grambling', nickname: 'Tigers' },
  { code: 'GT', location_name: 'Georgia Tech', nickname: 'Yellow Jackets' },
  { code: 'GTWN', location_name: 'Georgetown', nickname: 'Hoyas' },
  { code: 'GW', location_name: 'George Washington', nickname: 'Revolutionaries' },
  { code: 'HAMP', location_name: 'Hampton', nickname: 'Pirates' },
  { code: 'HARV', location_name: 'Harvard', nickname: 'Crimson' },
  { code: 'HAW', location_name: 'Hawai\'i', nickname: 'Rainbow Warriors' },
  { code: 'HC', location_name: 'Holy Cross', nickname: 'Crusaders' },
  { code: 'HCU', location_name: 'Houston Christian', nickname: 'Huskies' },
  { code: 'HOF', location_name: 'Hofstra', nickname: 'Pride' },
  { code: 'HOU', location_name: 'Houston', nickname: 'Cougars' },
  { code: 'HOW', location_name: 'Howard', nickname: 'Bison' },
  { code: 'HP', location_name: 'High Point', nickname: 'Panthers' },
  { code: 'IDHO', location_name: 'Idaho', nickname: 'Vandals' },
  { code: 'IDST', location_name: 'Idaho St.', nickname: 'Bengals' },
  { code: 'ILL', location_name: 'Illinois', nickname: 'Fighting Illini' },
  { code: 'ILST', location_name: 'Illinois St.', nickname: 'Redbirds' },
  { code: 'IND', location_name: 'Indiana', nickname: 'Hoosiers' },
  { code: 'INST', location_name: 'Indiana St.', nickname: 'Sycamores' },
  { code: 'IONA', location_name: 'Iona', nickname: 'Gaels' },
  { code: 'IOWA', location_name: 'Iowa', nickname: 'Hawkeyes' },
  { code: 'ISU', location_name: 'Iowa St.', nickname: 'Cyclones' },
  { code: 'IUI', location_name: 'IU Indianapolis', nickname: 'Jaguars' },
  { code: 'IW', location_name: 'Incarnate Word', nickname: 'Cardinals' },
  { code: 'JAC', location_name: 'Jacksonville', nickname: 'Dolphins' },
  { code: 'JKST', location_name: 'Jackson St.', nickname: 'Tigers' },
  { code: 'JMU', location_name: 'James Madison', nickname: 'Dukes' },
  { code: 'JVST', location_name: 'Jacksonville St.', nickname: 'Gamecocks' },
  { code: 'KENT', location_name: 'Kent St.', nickname: 'Golden Flashes' },
  { code: 'KSU', location_name: 'Kansas St.', nickname: 'Wildcats' },
  { code: 'KSW', location_name: 'Kennesaw St.', nickname: 'Owls' },
  { code: 'KU', location_name: 'Kansas', nickname: 'Jayhawks' },
  { code: 'LA', location_name: 'Louisiana', nickname: 'Ragin\' Cajuns' },
  { code: 'LAF', location_name: 'Lafayette', nickname: 'Leopards' },
  { code: 'LAM', location_name: 'Lamar', nickname: 'Cardinals' },
  { code: 'LASAL', location_name: 'La Salle', nickname: 'Explorers' },
  { code: 'LBS', location_name: 'Long Beach St.', nickname: 'Beach' },
  { code: 'LEH', location_name: 'Lehigh', nickname: 'Mountain Hawks' },
  { code: 'LIB', location_name: 'Liberty', nickname: 'Flames' },
  { code: 'LIPS', location_name: 'Lipscomb', nickname: 'Bisons' },
  { code: 'LIU', location_name: 'Long Island', nickname: 'Sharks' },
  { code: 'LMC', location_name: 'Le Moyne', nickname: 'Dolphins' },
  { code: 'LONG', location_name: 'Longwood', nickname: 'Lancers' },
  { code: 'LOU', location_name: 'Louisville', nickname: 'Cardinals' },
  { code: 'LOYIL', location_name: 'Loyola Chicago', nickname: 'Ramblers' },
  { code: 'LOYMR', location_name: 'Loyola Marymount', nickname: 'Lions' },
  { code: 'LSU', location_name: 'LSU', nickname: 'Tigers' },
  { code: 'LT', location_name: 'Louisiana Tech', nickname: 'Bulldogs' },
  { code: 'LUMD', location_name: 'Loyola (MD)', nickname: 'Greyhouds' },
  { code: 'Linden', location_name: 'Lindenwood', nickname: 'Lions' },
  { code: 'M-OH', location_name: 'Miami (OH)', nickname: 'Redhawks' },
  { code: 'MACK', location_name: 'Merrimack', nickname: 'Warriors' },
  { code: 'MANH', location_name: 'Manhattan', nickname: 'Jaspers' },
  { code: 'MARQ', location_name: 'Marquette', nickname: 'Golden Eagles' },
  { code: 'MCNS', location_name: 'McNeese', nickname: 'Cowboys' },
  { code: 'MEM', location_name: 'Memphis', nickname: 'Tigers' },
  { code: 'MER', location_name: 'Mercer', nickname: 'Bears' },
  { code: 'MHRT', location_name: 'Mercyhurst', nickname: 'Lakers' },
  { code: 'MIA', location_name: 'Miami', nickname: 'Hurricanes' },
  { code: 'MICH', location_name: 'Michigan', nickname: 'Wolverines' },
  { code: 'MINN', location_name: 'Minnesota', nickname: 'Golden Gophers' },
  { code: 'MISS', location_name: 'Ole Miss', nickname: 'Rebels' },
  { code: 'MIZZ', location_name: 'Missouri', nickname: 'Tigers' },
  { code: 'MNE', location_name: 'Maine', nickname: 'Black Bears' },
  { code: 'MOKC', location_name: 'Kansas City', nickname: 'Roos' },
  { code: 'MONM', location_name: 'Monmouth', nickname: 'Hawks' },
  { code: 'MONT', location_name: 'Montana', nickname: 'Grizzlies' },
  { code: 'MORE', location_name: 'Morehead St.', nickname: 'Eagles' },
  { code: 'MORG', location_name: 'Morgan St.', nickname: 'Bears' },
  { code: 'MOST', location_name: 'Missouri St.', nickname: 'Bears' },
  { code: 'MRSH', location_name: 'Marshall', nickname: 'Thundering Herd' },
  { code: 'MRST', location_name: 'Marist', nickname: 'Red Foxes' },
  { code: 'MSST', location_name: 'Mississippi St.', nickname: 'Bulldogs' },
  { code: 'MSU', location_name: 'Michigan St.', nickname: 'Spartans' },
  { code: 'MTST', location_name: 'Montana St.', nickname: 'Bobcats' },
  { code: 'MTSTM', location_name: 'Mount St. Mary\'s', nickname: 'Mountaineers' },
  { code: 'MTSU', location_name: 'Middle Tennessee', nickname: 'Blue Raiders' },
  { code: 'MURR', location_name: 'Murray St.', nickname: 'Racers' },
  { code: 'MVSU', location_name: 'Mississippi Valley St.', nickname: 'Delta Devils' },
  { code: 'NA', location_name: 'North Alabama', nickname: 'Lions' },
  { code: 'NAU', location_name: 'Northern Arizona', nickname: 'Lumberjacks' },
  { code: 'NAVY', location_name: 'Navy', nickname: 'Midshipmen' },
  { code: 'NCAT', location_name: 'North Carolina A&T', nickname: 'Aggies' },
  { code: 'NCCU', location_name: 'North Carolina Central', nickname: 'Eagles' },
  { code: 'NCST', location_name: 'NC St.', nickname: 'Wolfpack' },
  { code: 'ND', location_name: 'Notre Dame', nickname: 'Fighting Irish' },
  { code: 'NDSU', location_name: 'North Dakota St.', nickname: 'Bison' },
  { code: 'NEAS', location_name: 'Northeastern', nickname: 'Huskies' },
  { code: 'NEB', location_name: 'Nebraska', nickname: 'Cornhuskers' },
  { code: 'NEOM', location_name: 'Omaha', nickname: 'Mavericks' },
  { code: 'NEV', location_name: 'Nevada', nickname: 'Wolf Pack' },
  { code: 'NIAG', location_name: 'Niagara', nickname: 'Purple Eagles' },
  { code: 'NICH', location_name: 'Nicholls', nickname: 'Colonels' },
  { code: 'NIU', location_name: 'Northern Illinois', nickname: 'Huskies' },
  { code: 'NJIT', location_name: 'NJIT', nickname: 'Highlanders' },
  { code: 'NKU', location_name: 'Northern Kentucky', nickname: 'Norse' },
  { code: 'NMSU', location_name: 'New Mexico St.', nickname: 'Aggies' },
  { code: 'NORF', location_name: 'Norfolk St.', nickname: 'Spartans' },
  { code: 'NOVA', location_name: 'Villanova', nickname: 'Wildcats' },
  { code: 'NW', location_name: 'Northwestern', nickname: 'Wildcats' },
  { code: 'NWST', location_name: 'Northwestern St.', nickname: 'Demons' },
  { code: 'OAKD', location_name: 'Oakland', nickname: 'Golden Grizzlies' },
  { code: 'ODU', location_name: 'Old Dominion', nickname: 'Monarchs' },
  { code: 'OHIO', location_name: 'Ohio', nickname: 'Bobcats' },
  { code: 'OKLA', location_name: 'Oklahoma', nickname: 'Sooners' },
  { code: 'OKST', location_name: 'Oklahoma St.', nickname: 'Cowboys' },
  { code: 'ORAL', location_name: 'Oral Roberts', nickname: 'Golden Eagles' },
  { code: 'ORE', location_name: 'Oregon', nickname: 'Ducks' },
  { code: 'ORST', location_name: 'Oregon St.', nickname: 'Beavers' },
  { code: 'OSU', location_name: 'Ohio St.', nickname: 'Buckeyes' },
  { code: 'PAC', location_name: 'Pacific', nickname: 'Tigers' },
  { code: 'PEAY', location_name: 'Austin Peay', nickname: 'Governors' },
  { code: 'PENN', location_name: 'Pennsylvania', nickname: 'Quakers' },
  { code: 'PEPP', location_name: 'Pepperdine', nickname: 'Waves' },
  { code: 'PFW', location_name: 'Purdue Fort Wayne', nickname: 'Mastodons' },
  { code: 'PITT', location_name: 'Pittsburgh', nickname: 'Panthers' },
  { code: 'PORT', location_name: 'Portland', nickname: 'Pirates' },
  { code: 'PRES', location_name: 'Presbyterian', nickname: 'Blue Hose' },
  { code: 'PRIN', location_name: 'Princeton', nickname: 'Tigers' },
  { code: 'PROV', location_name: 'Providence', nickname: 'Friars' },
  { code: 'PRST', location_name: 'Portland St.', nickname: 'Vikings' },
  { code: 'PSU', location_name: 'Penn St.', nickname: 'Nittany Lions' },
  { code: 'PUR', location_name: 'Purdue', nickname: 'Boilermakers' },
  { code: 'PVAM', location_name: 'Prairie View A&M', nickname: 'Panthers' },
  { code: 'QNNC', location_name: 'Queens', nickname: 'Royals' },
  { code: 'QPAC', location_name: 'Quinnipiac', nickname: 'Bobcats' },
  { code: 'RADF', location_name: 'Radford', nickname: 'Highlanders' },
  { code: 'RDER', location_name: 'Rider', nickname: 'Broncs' },
  { code: 'RICE', location_name: 'Rice', nickname: 'Owls' },
  { code: 'RICH', location_name: 'Richmond', nickname: 'Spiders' },
  { code: 'RMU', location_name: 'Robert Morris', nickname: 'Colonials' },
  { code: 'RUTG', location_name: 'Rutgers', nickname: 'Scarlet Knights' },
  { code: 'SAC', location_name: 'Sacramento St.', nickname: 'Hornets' },
  { code: 'SAM', location_name: 'Samford', nickname: 'Bulldogs' },
  { code: 'SC', location_name: 'Santa Clara', nickname: 'Broncos' },
  { code: 'SCAR', location_name: 'South Carolina', nickname: 'Gamecocks' },
  { code: 'SCST', location_name: 'South Carolina St.', nickname: 'Bulldogs' },
  { code: 'SDAK', location_name: 'South Dakota', nickname: 'Coyotes' },
  { code: 'SDKS', location_name: 'South Dakota St.', nickname: 'Jackrabbits' },
  { code: 'SDSU', location_name: 'San Diego St.', nickname: 'Aztecs' },
  { code: 'SELA', location_name: 'Southeastern Louisiana', nickname: 'Lions' },
  { code: 'SEMO', location_name: 'Southeast Missouri St.', nickname: 'Redhawks' },
  { code: 'SF', location_name: 'San Francisco', nickname: 'Dons' }, 
  { code: 'SFA', location_name: 'Stephen F. Austin', nickname: 'Lumberjacks' },
  { code: 'SFU', location_name: 'St. Francis', nickname: 'Red Flash' },
  { code: 'SH', location_name: 'Seton Hall', nickname: 'Pirates' },
  { code: 'SHSU', location_name: 'Sam Houston St.', nickname: 'Bearkats' },
  { code: 'SHU', location_name: 'Sacred Heart', nickname: 'Pioneers' },
  { code: 'SIEN', location_name: 'Siena', nickname: 'Saints' },
  { code: 'SIU', location_name: 'Southern Illinois', nickname: 'Salukis' },
  { code: 'SIUE', location_name: 'SIU Edwardsville', nickname: 'Cougars' },
  { code: 'SJPA', location_name: 'St. Joseph\'s', nickname: 'Hawks' },
  { code: 'SJSU', location_name: 'San Jose St.', nickname: 'Spartans' },
  { code: 'SJU', location_name: 'St. John\'s', nickname: 'Red Storm' },
  { code: 'SMU', location_name: 'SMU', nickname: 'Mustangs' },
  { code: 'SOIN', location_name: 'Southern Indiana', nickname: 'Screaming Eagles' },
  { code: 'SOU', location_name: 'Southern', nickname: 'Jaguars' },
  { code: 'STAN', location_name: 'Stanford', nickname: 'Cardinal' },
  { code: 'STBON', location_name: 'St. Bonaventure', nickname: 'Bonnies' },
  { code: 'STET', location_name: 'Stetson', nickname: 'Hatters' },
  { code: 'STLOU', location_name: 'St. Louis', nickname: 'Billikens' },
  { code: 'STMCA', location_name: 'St. Mary\'s', nickname: 'Gaels' },
  { code: 'STMN', location_name: 'St. Thomas', nickname: 'Tommies' },
  { code: 'STNH', location_name: 'Stonehill', nickname: 'Skyhaws' },
  { code: 'STON', location_name: 'Stony Brook', nickname: 'Seawolves' },
  { code: 'STPE', location_name: 'St. Peter\'s', nickname: 'Peacocks' },
  { code: 'STTL', location_name: 'Seattle U', nickname: 'Redhawks' },
  { code: 'SUU', location_name: 'Southern Utah', nickname: 'Thunderbirds' },
  { code: 'SYR', location_name: 'Syracuse', nickname: 'Orange' },
  { code: 'TAMU', location_name: 'Texas A&M', nickname: 'Aggies' },
  { code: 'TAR', location_name: 'Tarleton St.', nickname: 'Texans' },
  { code: 'TCU', location_name: 'TCU', nickname: 'Horned Frogs' },
  { code: 'TEM', location_name: 'Temple', nickname: 'Owls' },
  { code: 'TENN', location_name: 'Tennessee', nickname: 'Volunteers' },
  { code: 'TEX', location_name: 'Texas', nickname: 'Longhorns' },
  { code: 'TLSA', location_name: 'Tulsa', nickname: 'Golden Hurricane' },
  { code: 'TNST', location_name: 'Tennessee St.', nickname: 'Tigers' },
  { code: 'TNTC', location_name: 'Tennessee Tech', nickname: 'Golden Eagles' },
  { code: 'TOL', location_name: 'Toledo', nickname: 'Rockets' },
  { code: 'TOWS', location_name: 'Towson', nickname: 'Tigers' },
  { code: 'TRGV', location_name: 'UT Rio Grande Valley', nickname: 'Vaqueros' },
  { code: 'TROY', location_name: 'Troy', nickname: 'Trojans' },
  { code: 'TTU', location_name: 'Texas Tech', nickname: 'Red Raiders' },
  { code: 'TULN', location_name: 'Tulane', nickname: 'Green Wave' },
  { code: 'TXACC', location_name: 'Texas A&M Corpus Christi', nickname: 'Islanders' },
  { code: 'TXARL', location_name: 'UT Arlington', nickname: 'Mavericks' },
  { code: 'TXSO', location_name: 'Texas Southern', nickname: 'Tigers' },
  { code: 'TXST', location_name: 'Texas St.', nickname: 'Bobcats' },
  { code: 'UAB', location_name: 'UAB', nickname: 'Blazers' },
  { code: 'UALR', location_name: 'Little Rock', nickname: 'Trojans' },
  { code: 'UCA', location_name: 'Central Arkansas', nickname: 'Bears' },
  { code: 'UCD', location_name: 'UC Davis', nickname: 'Aggies' },
  { code: 'UCF', location_name: 'UCF', nickname: 'Knights' },
  { code: 'UCI', location_name: 'UC Irvine', nickname: 'Anteaters' },
  { code: 'UCLA', location_name: 'UCLA', nickname: 'Bruins' },
  { code: 'UCSD', location_name: 'UC San Diego', nickname: 'Tritons' },
  { code: 'UGA', location_name: 'Georgia', nickname: 'Bulldogs' },
  { code: 'UIC', location_name: 'UIC', nickname: 'Flames' },
  { code: 'UK', location_name: 'Kentucky', nickname: 'Wildcats' },
  { code: 'ULM', location_name: 'UL Monroe', nickname: 'Warhawks' },
  { code: 'UMASS', location_name: 'Massachusetts', nickname: 'Minutemen' },
  { code: 'UMBC', location_name: 'UMBC', nickname: 'Retrievers' },
  { code: 'UMD', location_name: 'Maryland', nickname: 'Terrapins' },
  { code: 'UMES', location_name: 'Maryland Eastern Shore', nickname: 'Hawks' },
  { code: 'UMLW', location_name: 'UMass Lowell', nickname: 'River Hawks' },
  { code: 'UNC', location_name: 'North Carolina', nickname: 'Tar Heels' },
  { code: 'UNCA', location_name: 'UNC Asheville', nickname: 'Bulldogs' },
  { code: 'UNCG', location_name: 'UNC Greensboro', nickname: 'Spartans' },
  { code: 'UNCW', location_name: 'UNC Wilmington', nickname: 'Seahawks' },
  { code: 'UNCO', location_name: 'Northern Colorado', nickname: 'Bears' },
  { code: 'UND', location_name: 'North Dakota', nickname: 'Fighting Hawks' },
  { code: 'UNFL', location_name: 'North Florida', nickname: 'Ospreys' },
  { code: 'UNH', location_name: 'New Hampshire', nickname: 'Wildcats' },
  { code: 'UNHV', location_name: 'New Haven', nickname: 'Chargers' },
  { code: 'UNI', location_name: 'Northern Iowa', nickname: 'Panthers' },
  { code: 'UNLV', location_name: 'UNLV', nickname: 'Rebels' },
  { code: 'UNM', location_name: 'New Mexico', nickname: 'Lobos' },
  { code: 'UNO', location_name: 'New Orleans', nickname: 'Privateers' },
  { code: 'UNT', location_name: 'North Texas', nickname: 'Mean Green' },
  { code: 'URI', location_name: 'Rhode Island', nickname: 'Rams' },
  { code: 'USA', location_name: 'South Alabama', nickname: 'Jaguars' },
  { code: 'USC', location_name: 'USC', nickname: 'Trojans' },
  { code: 'USCU', location_name: 'South Carolina Upstate', nickname: 'Spartans' },
  { code: 'USF', location_name: 'South Florida', nickname: 'Bulls' },
  { code: 'USD', location_name: 'San Diego', nickname: 'Toreros' },
  { code: 'USM', location_name: 'Southern Miss', nickname: 'Golden Eagles' },
  { code: 'USU', location_name: 'Utah St.', nickname: 'Aggies' },
  { code: 'UTAH', location_name: 'Utah', nickname: 'Utes' },
  { code: 'UTEP', location_name: 'UTEP', nickname: 'Miners' },
  { code: 'UTM', location_name: 'UT Martin', nickname: 'Skyhawks' },
  { code: 'UTSA', location_name: 'UTSA', nickname: 'Roadrunners' },
  { code: 'UTU', location_name: 'Utah Tech', nickname: 'Trailblazers' },
  { code: 'UVA', location_name: 'Virginia', nickname: 'Cavaliers' },
  { code: 'UVSU', location_name: 'Utah Valley', nickname: 'Wolverines' },
  { code: 'UWGB', location_name: 'Green Bay', nickname: 'Phoenix' },
  { code: 'UWM', location_name: 'Milwaukee', nickname: 'Panthers' },
  { code: 'VALP', location_name: 'Valparaiso', nickname: 'Beacons' },
  { code: 'VAN', location_name: 'Vanderbilt', nickname: 'Commodores' },
  { code: 'VCU', location_name: 'Virginia Commonwealth', nickname: 'Rams' },
  { code: 'VMI', location_name: 'VMI', nickname: 'Keydets' },
  { code: 'VRMT', location_name: 'Vermont', nickname: 'Catamounts' },
  { code: 'VT', location_name: 'Virginia Tech', nickname: 'Hokies' },
  { code: 'WAG', location_name: 'Wagner', nickname: 'Seahawks' },
  { code: 'WAKE', location_name: 'Wake Forrest', nickname: 'Demon Deacons' },
  { code: 'WASH', location_name: 'Washington', nickname: 'Huskies' },
  { code: 'WCHST', location_name: 'Wichita St.', nickname: 'Shockers' },
  { code: 'WCU', location_name: 'Western Carolina', nickname: 'Catamounts' },
  { code: 'WEB', location_name: 'Weber St.', nickname: 'Wildcats' },
  { code: 'WEBB', location_name: 'Gardner-Webb', nickname: 'Runnin\' Bulldogs' },
  { code: 'WEGA', location_name: 'Western Georgia', nickname: 'Wolves' },
  { code: 'WINT', location_name: 'Winthrop', nickname: 'Eagles' },
  { code: 'WIS', location_name: 'Wisconsin', nickname: 'Badgers' },
  { code: 'WIU', location_name: 'Western Illinois', nickname: 'Leathernecks' },
  { code: 'WKU', location_name: 'Western Kentucky', nickname: 'Hilltoppers' },
  { code: 'WMRY', location_name: 'William & Mary', nickname: 'Tribe' },
  { code: 'WMU', location_name: 'Western Michigan', nickname: 'Broncos' },
  { code: 'WOF', location_name: 'Wofford', nickname: 'Terriers' },
  { code: 'WRIG', location_name: 'Wright St.', nickname: 'Raiders' },
  { code: 'WSU', location_name: 'Washington St.', nickname: 'Cougars' },
  { code: 'WVU', location_name: 'West Virginia', nickname: 'Mountaineers' },
  { code: 'WYO', location_name: 'Wyoming', nickname: 'Cowboys' },
  { code: 'XAV', location_name: 'Xavier', nickname: 'Musketeers' },
  { code: 'YALE', location_name: 'Tale', nickname: 'Bulldogs' },
  { code: 'YSU', location_name: 'Youngstown St.', nickname: 'Penguins' },
]

ncaa_teams.each do |attrs|
  team = Team.find_or_create_by!(code: attrs[:code]) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
  
  # Associate with both football and basketball leagues
  team.leagues << ncaaf unless team.leagues.include?(ncaaf)
  team.leagues << ncaam unless team.leagues.include?(ncaam)
end