mlb = League.find_by!(code: 'mlb')
nfl = League.find_by!(code: 'nfl')
ncaaf = League.find_by!(code: 'ncaaf')

mlb_teams = [
  { code: 'ATH', location_name: '',  nickname: 'Athletics' },
  { code: 'ARI', location_name: 'Arizona', nickname: 'Diamondbacks' },
  { code: 'ATL', location_name: 'Atlanta', nickname: 'Braves' },
  { code: 'BAL', location_name: 'Baltimore', nickname: 'Orioles' },
  { code: 'BOS', location_name: 'Boston', nickname: 'Red Sox' },
  { code: 'CHC', location_name: 'Chicago', nickname: 'Cubs' },
  { code: 'CHW', location_name: 'Chicago', nickname: 'White Sox' },
  { code: 'CIN', location_name: 'Cincinnati', nickname: 'Reds' },
  { code: 'CLE', location_name: 'Cleveland', nickname: 'Guardians' },
  { code: 'COL', location_name: 'Colorado', nickname: 'Rockies' },
  { code: 'DET', location_name: 'Detroit', nickname: 'Tigers' },
  { code: 'HOU', location_name: 'Houston', nickname: 'Astros' },
  { code: 'KCR', location_name: 'Kansas City', nickname: 'Royals' },
  { code: 'LAA', location_name: 'Los Angeles', nickname: 'Angels' },
  { code: 'LAD', location_name: 'Los Angeles', nickname: 'Dodgers' },
  { code: 'MIA', location_name: 'Miami', nickname: 'Marlins' },
  { code: 'MIL', location_name: 'Milwaukee', nickname: 'Brewers' },
  { code: 'MIN', location_name: 'Minnesota', nickname: 'Twins' },
  { code: 'NYM', location_name: 'New York', nickname: 'Mets' },
  { code: 'NYY', location_name: 'New York', nickname: 'Yankees' },
  { code: 'PHI', location_name: 'Philadelphia', nickname: 'Phillies' },
  { code: 'PIT', location_name: 'Pittsburgh', nickname: 'Pirates' },
  { code: 'SEA', location_name: 'Seattle', nickname: 'Mariners' },
  { code: 'SDP', location_name: 'San Diego', nickname: 'Padres' },
  { code: 'SFG', location_name: 'San Francisco', nickname: 'Giants' },
  { code: 'STL', location_name: 'Saint Louis', nickname: 'Cardinals' },
  { code: 'TBR', location_name: 'Tampa Bay', nickname: 'Rays' },
  { code: 'TEX', location_name: 'Texas', nickname: 'Rangers' },
  { code: 'TOR', location_name: 'Toronto', nickname: 'Blue Jays' },
  { code: 'WSN', location_name: 'Washington', nickname: 'Nationals' }
]

mlb_teams.each do |attrs|
  Team.find_or_create_by!(code: attrs[:code], league: mlb) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
end

nlf_teams = [
  { code: 'ARI', location_name: 'Arizona',  nickname: 'Cardinals' },
  { code: 'ATL', location_name: 'Atlanta',  nickname: 'Falcons' },
  { code: 'BAL', location_name: 'Baltimore',  nickname: 'Ravens' },
  { code: 'BUF', location_name: 'Buffalo',  nickname: 'Bills' },
  { code: 'CAR', location_name: 'Carolina',  nickname: 'Panthers' },
  { code: 'CHI', location_name: 'Chicago',  nickname: 'Bears' },
  { code: 'CIN', location_name: 'Cincinnati',  nickname: 'Bengals' },
  { code: 'CLE', location_name: 'Cleveland',  nickname: 'Browns' },
  { code: 'DAL', location_name: 'Dallas',  nickname: 'Cowboys' },
  { code: 'DEN', location_name: 'Denver',  nickname: 'Broncos' },
  { code: 'DET', location_name: 'Detroit',  nickname: 'Lions' },
  { code: 'GNB', location_name: 'Green Bay',  nickname: 'Packers' },
  { code: 'HOU', location_name: 'Houston',  nickname: 'Texans' },
  { code: 'IND', location_name: 'Indianapolis',  nickname: 'Colts' },
  { code: 'JAX', location_name: 'Jacksonville',  nickname: 'Jaguars' },
  { code: 'KAN', location_name: 'Kansas City',  nickname: 'Chiefs' },
  { code: 'LAC', location_name: 'Los Angeles',  nickname: 'Chargers' },
  { code: 'LAR', location_name: 'Los Angeles',  nickname: 'Rams' },
  { code: 'LVR', location_name: 'Las Vegas',  nickname: 'Raiders' },
  { code: 'MIA', location_name: 'Miami',  nickname: 'Dolphins' },
  { code: 'MIN', location_name: 'Minnesota',  nickname: 'Vikings' },
  { code: 'NOR', location_name: 'New Orleans',  nickname: 'Saints' },
  { code: 'NWE', location_name: 'New England',  nickname: 'Patriots' },
  { code: 'NYG', location_name: 'New York',  nickname: 'Giants' },
  { code: 'NYJ', location_name: 'New York',  nickname: 'Jets' },
  { code: 'PHI', location_name: 'Philadelphia',  nickname: 'Eagles' },
  { code: 'PIT', location_name: 'Pittsburgh',  nickname: 'Steelers' },
  { code: 'SEA', location_name: 'Seattle',  nickname: 'Seahawks' },
  { code: 'SFO', location_name: 'San Francisco',  nickname: '49ers' },
  { code: 'TAM', location_name: 'Tampa Bay',  nickname: 'Buccaneers' },
  { code: 'TEN', location_name: 'Tennessee',  nickname: 'Titans' },
  { code: 'WAS', location_name: 'Washington',  nickname: 'Commanders' }
]

nlf_teams.each do |attrs|
  Team.find_or_create_by!(code: attrs[:code], league: nfl) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
end

ncaaf_teams = [
  { code: 'AAMU', location_name: 'Alabama A&M', nickname: 'Bulldogs' },
  { code: 'ACU', location_name: 'Abilene Christian', nickname: 'Wildcats' },
  { code: 'AFA', location_name: 'Air Force', nickname: 'Falcons' },
  { code: 'AKR', location_name: 'Akron', nickname: 'Zips' },
  { code: 'ALBY', location_name: 'Albany', nickname: 'Great Danes' },
  { code: 'ALST', location_name: 'Alabama St.', nickname: 'Hornets' },
  { code: 'APP', location_name: 'App St.', nickname: 'Mountaineers' },
  { code: 'ARIZ', location_name: 'Arizona', nickname: 'Wildcats' },
  { code: 'ARK', location_name: 'Arkansas', nickname: 'Razorbacks' },
  { code: 'ARMY', location_name: 'Army', nickname: 'Black Knights' },
  { code: 'ARPB', location_name: 'Arkansas-Pine Bluff', nickname: 'Golden Lions' },
  { code: 'ARST', location_name: 'Arkansas St.', nickname: 'Red Wolves' },
  { code: 'ASU', location_name: 'Arizona St.', nickname: 'Sun Devils' },
  { code: 'AUB', location_name: 'Auburn', nickname: 'Tigers' },
  { code: 'BALL', location_name: 'Ball St.', nickname: 'Cardinals' },
  { code: 'BAMA', location_name: 'Alabama', nickname: 'Crimson Tide' },
  { code: 'BAY', location_name: 'Baylor', nickname: 'Bears' },
  { code: 'BC', location_name: 'Boston College', nickname: 'Eagles' },
  { code: 'BGSU', location_name: 'Bowling Green', nickname: 'Falcons' },
  { code: 'BRY', location_name: 'Bryant', nickname: 'Bulldogs' },
  { code: 'BSU', location_name: 'Boise St.', nickname: 'Broncos' },
  { code: 'BUCK', location_name: 'Bucknell', nickname: 'Bison' },
  { code: 'BUFF', location_name: 'Buffalo', nickname: 'Bulls' },
  { code: 'BYU', location_name: 'Brigham Young', nickname: 'Cougars' },
  { code: 'CAL', location_name: 'California', nickname: 'Bears' },
  { code: 'CAMP', location_name: 'Campbell', nickname: 'Fighting Camels' },
  { code: 'CCAR', location_name: 'Coastal Carolina', nickname: 'Chanticleers' },
  { code: 'CCTST', location_name: 'Central Connecticut', nickname: 'Blue Devils' },
  { code: 'CHAR', location_name: 'Charlotte', nickname: '49ers' },
  { code: 'CHAT', location_name: 'Chattanooga', nickname: 'Mocs' },
  { code: 'CHSO', location_name: 'Charleston Southern', nickname: 'Buccaneers' },
  { code: 'CIN', location_name: 'Cincinnati', nickname: 'Bearcats' },
  { code: 'CLEM', location_name: 'Clemson', nickname: 'Tigers' },
  { code: 'CMU', location_name: 'Central Michigan', nickname: 'Chippewas' },
  { code: 'COLO', location_name: 'Colorado', nickname: 'Buffaloes' },
  { code: 'CONN', location_name: 'Connecticut', nickname: 'Huskies' },
  { code: 'COOK', location_name: 'Bethune-Cookman', nickname: 'Wildcats' },
  { code: 'CP', location_name: 'Cal Poly', nickname: 'Mustangs' },
  { code: 'CSU', location_name: 'Colorado St.', nickname: 'Rams' },
  { code: 'DEL', location_name: 'Delaware', nickname: 'Blue Hens' },
  { code: 'DSU', location_name: 'Delaware St.', nickname: 'Hornets' },
  { code: 'DUKE', location_name: 'Duke', nickname: 'Blue Devils' },
  { code: 'DUQ', location_name: 'Duquesne', nickname: 'Dukes' },
  { code: 'ECU', location_name: 'East Carolina', nickname: 'Pirates' },
  { code: 'EKY', location_name: 'Eastern Kentucky', nickname: 'Colonels' },
  { code: 'ELON', location_name: 'Elon', nickname: 'Phoenix' },
  { code: 'EMU', location_name: 'Eastern Michigan', nickname: 'Eagles' },
  { code: 'ETAM', location_name: 'East Texas A&M', nickname: 'Lions' },
  { code: 'ETNST', location_name: 'East Tennessee St.', nickname: 'Buccaneers' },
  { code: 'EWU', location_name: 'Eastern Washington', nickname: 'Eagles' },
  { code: 'FAMU', location_name: 'Florida A&M', nickname: 'Rattlers' },
  { code: 'FAU', location_name: 'Florida Atlantic', nickname: 'Owls' },
  { code: 'FIU', location_name: 'Florida International', nickname: 'Panthers' },
  { code: 'FLA', location_name: 'Florida', nickname: 'Gators' },
  { code: 'FOR', location_name: 'Fordham', nickname: 'Rams' },
  { code: 'FRES', location_name: 'Fresno St.', nickname: 'Bulldogs' },
  { code: 'FSU', location_name: 'Florida St.', nickname: 'Seminoles' },
  { code: 'GASO', location_name: 'Georgia Southern', nickname: 'Eagles' },
  { code: 'GAST', location_name: 'Georgia St.', nickname: 'Panthers' },
  { code: 'GRAM', location_name: 'Grambling', nickname: 'Tigers' },
  { code: 'GT', location_name: 'Georgia Tech', nickname: 'Yellow Jackets' },
  { code: 'HAW', location_name: 'Hawai\'i', nickname: 'Rainbow Warriors' },
  { code: 'HC', location_name: 'Holy Cross', nickname: 'Crusaders' },
  { code: 'HOU', location_name: 'Houston', nickname: 'Cougars' },
  { code: 'HOW', location_name: 'Howard', nickname: 'Bison' },
  { code: 'IDHO', location_name: 'Idaho', nickname: 'Vandals' },
  { code: 'IDST', location_name: 'Idaho St.', nickname: 'Bengals' },
  { code: 'ILL', location_name: 'Illinois', nickname: 'Fighting Illini' },
  { code: 'ILST', location_name: 'Illinois St.', nickname: 'Redbirds' },
  { code: 'IND', location_name: 'Indiana', nickname: 'Hoosiers' },
  { code: 'IOWA', location_name: 'Iowa', nickname: 'Hawkeyes' },
  { code: 'ISU', location_name: 'Iowa St.', nickname: 'Cyclones' },
  { code: 'JKST', location_name: 'Jackson St.', nickname: 'Tigers' },
  { code: 'JMU', location_name: 'James Madison', nickname: 'Dukes' },
  { code: 'JVST', location_name: 'Jacksonville St.', nickname: 'Gamecocks' },
  { code: 'KENT', location_name: 'Kent St.', nickname: 'Golden Flashes' },
  { code: 'KSU', location_name: 'Kansas St.', nickname: 'Wildcats' },
  { code: 'KSW', location_name: 'Kennesaw St.', nickname: 'Owls' },
  { code: 'KU', location_name: 'Kansas', nickname: 'Jayhawks' },
  { code: 'LA', location_name: 'Louisiana', nickname: 'Ragin\' Cajuns' },
  { code: 'LAF', location_name: 'Lafayette', nickname: 'Leopards' },
  { code: 'LAM', location_name: 'Lamar', nickname: 'Cardinals' },
  { code: 'LIB', location_name: 'Liberty', nickname: 'Flames' },
  { code: 'LIU', location_name: 'Long Island', nickname: 'Sharks' },
  { code: 'LOU', location_name: 'Louisville', nickname: 'Cardinals' },
  { code: 'LSU', location_name: 'LSU', nickname: 'Tigers' },
  { code: 'LT', location_name: 'Louisiana Tech', nickname: 'Bulldogs' },
  { code: 'Linden', location_name: 'Lindenwood', nickname: 'Lions' },
  { code: 'M-OH', location_name: 'Miami (OH)', nickname: 'Redhawks' },
  { code: 'MACK', location_name: 'Merrimack', nickname: 'Warriors' },
  { code: 'MCNS', location_name: 'McNeese', nickname: 'Cowboys' },
  { code: 'MEM', location_name: 'Memphis', nickname: 'Tigers' },
  { code: 'MIA', location_name: 'Miami', nickname: 'Hurricanes' },
  { code: 'MICH', location_name: 'Michigan', nickname: 'Wolverines' },
  { code: 'MINN', location_name: 'Minnesota', nickname: 'Golden Gophers' },
  { code: 'MISS', location_name: 'Ole Miss', nickname: 'Rebels' },
  { code: 'MIZZ', location_name: 'Missouri', nickname: 'Tigers' },
  { code: 'MNE', location_name: 'Maine', nickname: 'Black Bears' },
  { code: 'MORG', location_name: 'Morgan St.', nickname: 'Bears' },
  { code: 'MOST', location_name: 'Missouri St.', nickname: 'Bears' },
  { code: 'MRSH', location_name: 'Marshall', nickname: 'Thundering Herd' },
  { code: 'MSST', location_name: 'Mississippi St.', nickname: 'Bulldogs' },
  { code: 'MSU', location_name: 'Michigan St.', nickname: 'Spartans' },
  { code: 'MTST', location_name: 'Montana St.', nickname: 'Bobcats' },
  { code: 'MTSU', location_name: 'Middle Tennessee', nickname: 'Blue Raiders' },
  { code: 'NA', location_name: 'North Alabama', nickname: 'Lions' },
  { code: 'NAU', location_name: 'Northern Arizona', nickname: 'Lumberjacks' },
  { code: 'NAVY', location_name: 'Navy', nickname: 'Midshipmen' },
  { code: 'NCAT', location_name: 'North Carolina A&T', nickname: 'Aggies' },
  { code: 'NCCU', location_name: 'North Carolina Central', nickname: 'Eagles' },
  { code: 'NCST', location_name: 'NC St.', nickname: 'Wolfpack' },
  { code: 'ND', location_name: 'Notre Dame', nickname: 'Fighting Irish' },
  { code: 'NEB', location_name: 'Nebraska', nickname: 'Cornhuskers' },
  { code: 'NEV', location_name: 'Nevada', nickname: 'Wolf Pack' },
  { code: 'NICH', location_name: 'Nicholls', nickname: 'Colonels' },
  { code: 'NIU', location_name: 'Northern Illinois', nickname: 'Huskies' },
  { code: 'NMSU', location_name: 'New Mexico St.', nickname: 'Aggies' },
  { code: 'NW', location_name: 'Northwestern', nickname: 'Wildcats' },
  { code: 'NWST', location_name: 'Northwestern St.', nickname: 'Demons' },
  { code: 'ODU', location_name: 'Old Dominion', nickname: 'Monarchs' },
  { code: 'OHIO', location_name: 'Ohio', nickname: 'Bobcats' },
  { code: 'OKLA', location_name: 'Oklahoma', nickname: 'Sooners' },
  { code: 'OKST', location_name: 'Oklahoma St.', nickname: 'Cowboys' },
  { code: 'ORE', location_name: 'Oregon', nickname: 'Ducks' },
  { code: 'ORST', location_name: 'Oregon St.', nickname: 'Beavers' },
  { code: 'OSU', location_name: 'Ohio St.', nickname: 'Buckeyes' },
  { code: 'PEAY', location_name: 'Austin Peay', nickname: 'Governors' },
  { code: 'PITT', location_name: 'Pittsburgh', nickname: 'Panthers' },
  { code: 'PRST', location_name: 'Portland St.', nickname: 'Vikings' },
  { code: 'PSU', location_name: 'Penn St.', nickname: 'Nittany Lions' },
  { code: 'PUR', location_name: 'Purdue', nickname: 'Boilermakers' },
  { code: 'RICE', location_name: 'Rice', nickname: 'Owls' },
  { code: 'RMU', location_name: 'Robert Morris', nickname: 'Colonials' },
  { code: 'RUTG', location_name: 'Rutgers', nickname: 'Scarlet Knights' },
  { code: 'SAC', location_name: 'Sacramento St.', nickname: 'Hornets' },
  { code: 'SCAR', location_name: 'South Carolina', nickname: 'Gamecocks' },
  { code: 'SCST', location_name: 'South Carolina St.', nickname: 'Bulldogs' },
  { code: 'SDAK', location_name: 'South Dakota', nickname: 'Coyotes' },
  { code: 'SDSU', location_name: 'San Diego St.', nickname: 'Aztecs' },
  { code: 'SELA', location_name: 'Southeast Louisiana', nickname: 'Lions' },
  { code: 'SEMO', location_name: 'Southeast Missouri St.', nickname: 'Redhawks' },
  { code: 'SFA', location_name: 'Stephen F. Austin', nickname: 'Lumberjacks' },
  { code: 'SFU', location_name: 'Saint Francis', nickname: 'Red Flash' },
  { code: 'SHSU', location_name: 'Sam Houston St.', nickname: 'Bearkats' },
  { code: 'SIU', location_name: 'Southern Illinois', nickname: 'Salukis' },
  { code: 'SJSU', location_name: 'San Jose St.', nickname: 'Spartans' },
  { code: 'SMU', location_name: 'SMU', nickname: 'Mustangs' },
  { code: 'STAN', location_name: 'Stanford', nickname: 'Cardinal' },
  { code: 'STON', location_name: 'Stony Brook', nickname: 'Seawolves' },
  { code: 'SYR', location_name: 'Syracuse', nickname: 'Orange' },
  { code: 'TAMU', location_name: 'Texas A&M', nickname: 'Aggies' },
  { code: 'TAR', location_name: 'Tarleton St.', nickname: 'Texans' },
  { code: 'TCU', location_name: 'TCU', nickname: 'Horned Frogs' },
  { code: 'TEM', location_name: 'Temple', nickname: 'Owls' },
  { code: 'TENN', location_name: 'Tennessee', nickname: 'Volunteers' },
  { code: 'TEX', location_name: 'Texas', nickname: 'Longhorns' },
  { code: 'TLSA', location_name: 'Tulsa', nickname: 'Golden Hurricane' },
  { code: 'TOL', location_name: 'Toledo', nickname: 'Rockets' },
  { code: 'TROY', location_name: 'Troy', nickname: 'Trojans' },
  { code: 'TTU', location_name: 'Texas Tech', nickname: 'Red Raiders' },
  { code: 'TULN', location_name: 'Tulane', nickname: 'Green Wave' },
  { code: 'TXSO', location_name: 'Texas Southern', nickname: 'Tigers' },
  { code: 'TXST', location_name: 'Texas St.', nickname: 'Bobcats' },
  { code: 'UAB', location_name: 'UAB', nickname: 'Blazers' },
  { code: 'UCA', location_name: 'Central Arkansas', nickname: 'Bears' },
  { code: 'UCD', location_name: 'UC Davis', nickname: 'Aggies' },
  { code: 'UCF', location_name: 'UCF', nickname: 'Knights' },
  { code: 'UCLA', location_name: 'UCLA', nickname: 'Bruins' },
  { code: 'UGA', location_name: 'Georgia', nickname: 'Bulldogs' },
  { code: 'UK', location_name: 'Kentucky', nickname: 'Wildcats' },
  { code: 'ULM', location_name: 'UL Monroe', nickname: 'Warhawks' },
  { code: 'UMASS', location_name: 'Massachusetts', nickname: 'Minutemen' },
  { code: 'UMD', location_name: 'Maryland', nickname: 'Terrapins' },
  { code: 'UNC', location_name: 'North Carolina', nickname: 'Tar Heels' },
  { code: 'UNCO', location_name: 'Northern Colorado', nickname: 'Bears' },
  { code: 'UND', location_name: 'North Dakota', nickname: 'Fighting Hawks' },
  { code: 'UNI', location_name: 'Northern Iowa', nickname: 'Panthers' },
  { code: 'UNLV', location_name: 'UNLV', nickname: 'Rebels' },
  { code: 'UNM', location_name: 'New Mexico', nickname: 'Lobos' },
  { code: 'UNT', location_name: 'North Texas', nickname: 'Mean Green' },
  { code: 'USA', location_name: 'Soth Alabama', nickname: 'Jaguars' },
  { code: 'USC', location_name: 'USC', nickname: 'Trojans' },
  { code: 'USF', location_name: 'South Florida', nickname: 'Bulls' },
  { code: 'USM', location_name: 'Southern Miss', nickname: 'Golden Eagles' },
  { code: 'USU', location_name: 'Utah St.', nickname: 'Aggies' },
  { code: 'UTAH', location_name: 'Utah', nickname: 'Utes' },
  { code: 'UTEP', location_name: 'UTEP', nickname: 'Miners' },
  { code: 'UTM', location_name: 'UT Martin', nickname: 'Skyhawks' },
  { code: 'UTSA', location_name: 'UTSA', nickname: 'Roadrunners' },
  { code: 'UVA', location_name: 'Virginia', nickname: 'Cavaliers' },
  { code: 'VAN', location_name: 'Vanderbilt', nickname: 'Commodores' },
  { code: 'VMI', location_name: 'VMI', nickname: 'Keydets' },
  { code: 'VT', location_name: 'Virginia Tech', nickname: 'Hokies' },
  { code: 'WAG', location_name: 'Wagner', nickname: 'Seahawks' },
  { code: 'WAKE', location_name: 'Wake Forrest', nickname: 'Demon Deacons' },
  { code: 'WASH', location_name: 'Washington', nickname: 'Huskies' },
  { code: 'WCU', location_name: 'Western Carolina', nickname: 'Catamounts' },
  { code: 'WEB', location_name: 'Weber St.', nickname: 'Wildcats' },
  { code: 'WEBB', location_name: 'Gardner-Webb', nickname: 'Runnin\' Bulldogs' },
  { code: 'WIS', location_name: 'Wisconsin', nickname: 'Badgers' },
  { code: 'WIU', location_name: 'Western Illinois', nickname: 'Leathernecks' },
  { code: 'WKU', location_name: 'Western Kentucky', nickname: 'Hilltoppers' },
  { code: 'WMU', location_name: 'Western Michigan', nickname: 'Broncos' },
  { code: 'WSU', location_name: 'Washington St.', nickname: 'Cougars' },
  { code: 'WVU', location_name: 'West Virginia', nickname: 'Mountaineers' },
  { code: 'WYO', location_name: 'Wyoming', nickname: 'Cowboys' }
]

ncaaf_teams.each do |attrs|
  Team.find_or_create_by!(code: attrs[:code], league: ncaaf) do |t|
    t.location_name = attrs[:location_name]
    t.nickname = attrs[:nickname]
    t.active = true
  end
end