load Rails.root.join('db/seeds/sports.rb')
load Rails.root.join('db/seeds/leagues.rb')
load Rails.root.join('db/seeds/teams.rb')
load Rails.root.join('db/seeds/venues.rb')
load Rails.root.join('db/seeds/data_sources.rb')
load Rails.root.join('db/seeds/team_identifiers.rb')